### ISSUE TITLE
how to set dashboard base url?

### ISSUE THREAD

**Issue by andares** [emqx/emqx-dashboard#41]
We wanna visit emqx dashboard by url ```http://mydomain.com/emqadmin```, how to set base url？

**Comment by HJianBo** [comment]
Hi, @andares The EMQX don't care about the base URL. You can hang up a Proxy server in front of EMQX (For example Ngnix).

**Comment by andares** [comment]
but I try to do it, the resource load request is all be 404.

![图片](https://user-images.githubusercontent.com/7556505/54749935-114e2600-4c11-11e9-982f-8cbf118ac23c.png)

![图片](https://user-images.githubusercontent.com/7556505/54749954-2460f600-4c11-11e9-8784-340459cdd804.png)

![图片](https://user-images.githubusercontent.com/7556505/54749983-380c5c80-4c11-11e9-8847-8a30962f96d2.png)

the path is not append in url head.

my nginx proxy config:

```
    location ^~/emqadmin/ {
        proxy_pass              http://channel:18083/;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host $http_host;
    }

    location ^~/rmqadmin/ {
        proxy_pass              http://bus:15672/;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host $http_host;
    }

    location ^~/kadmin/ {
        proxy_pass              http://kadmin:1337/;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host $http_host;
    }
```

I have other web admin service, it's working fine. 😹

**Comment by zhanghongtong** [comment]
You also need to proxy static resource dependencies and the Dashboard API, just like this
```
location ^~/emqadmin/ {
        proxy_pass              http://channel:18083/;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host $http_host;
    }
location ^~/static/ {
        proxy_pass              http://channel:18083/static/;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host $http_host;
    }
location ^~/api/v3/ {
        proxy_pass              http://channel:18083/api/v3;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host $http_host;
    }
```

**Comment by zhanghongtong** [comment]
@andares This issue is resolved. I am going to close this issue. Please feel free to re-open if you still have the same trouble.

**Comment by andares** [comment]
I don't think so that the question is resolved. It's not "don't care about the base URL", it is "not support base url". As my example, nginx proxy point to rabbitmq admin and kong admin, they are working in the same domain, and the domain may be use for other app.

The rabbitmq admin is real "don't care about base url", it no need more setting. And kong admin can set a base url, and it's working fine too.

If I should proxy every resource for emq dashboard, that's not as good as use a separate domain. 😹

**Comment by CumpsD** [comment]
This isn't solved when you require root /static and /api/v3 to be mapped as well. That defeats the entire purpose of being able to map it. Now /api/v3 is just colliding with other /api paths on that same reverse proxy.

One option would be to not use absolute paths, or allow setting a base url.

**Comment by Ddystopia** [comment]
@Rory-Z other apps may also have `static` prefix, but your solution will redirect them to emqx, as well as it is a maintenance burden to enumerate all possible prefixes emqx might want.

**Comment by id** [comment]
@ysfscream FYI
